apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devops-capstone-app
  labels:
    app: udacity-devops-capstone-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity-devops-capstone-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity-devops-capstone-app
    spec:
      containers:
      - image: dibaroy/udacity_devops_capstone_app:latest
        imagePullPolicy: Always
        name: udacity-devops-capstone-app
        ports:
        - containerPort: 3000
          protocol: TCP
