apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::638224466109:role/udacity-devops-capstone-eks-node-NodeInstanceRole-15AR16QYFM2XP
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::638224466109:role/udacity-user
      username: udacity-user
      groups:
        - system:masters
